SuperOfficeDocs/superoffice-docs

docs/apps/getting-started/app-envir.md
=> Closing #79 added subsection about maintenance window to app-envir page

docs/apps/activate/helper-application.md
Fix for https://github.com/SuperOfficeDocs/feedback/issues/37
=> Fix broken image reference

docs/automation/trigger/index.md
Added more information to resolve : https://github.com/SuperOfficeDocs/crmscript/issues/62
=> Enchanced information

docs/mirroring/requirements.md
Fix for https://github.com/SuperOfficeDocs/feedback/issues/44
=> Fix spelling mistake and remove invalid requirement

docs/automation/includes/automation-intro.md, docs/automation/includes/macro-intro.md, docs/automation/macro/index.md, docs/automation/overview.md, docs/automation/toc.yml, docs/automation/trigger/set-validation-rules.md
=> Added terminology section to automation and populated macro index page

docs/document/templates/variables/for-service.md
See [#54](https://github.com/SuperOfficeDocs/feedback/issues/54)
=> Update examples of service variables, fix #54

docs/automation/crmscript/reference/CRMScript.NetServer.EventHandlerType.yml, docs/automation/trigger/reference/CRMScript.Event.Trigger.yml, docs/database/tables/enums/screenchoosertype.md
=> #225 added documentation for new triggers

docs/automation/crmscript/reference/CRMScript.Native.Notify.yml
=> Added new method #250

docs/automation/crmscript/reference/CRMScript.NetServer.NSAppointmentEntity.yml, docs/automation/crmscript/reference/CRMScript.NetServer.NSContactEntity.yml, docs/automation/crmscript/reference/CRMScript.NetServer.NSDocumentEntity.yml, docs/automation/crmscript/reference/CRMScript.NetServer.NSPersonEntity.yml, docs/automation/crmscript/reference/CRMScript.NetServer.NSProjectEntity.yml, docs/automation/crmscript/reference/CRMScript.NetServer.NSSaleEntity.yml, docs/automation/crmscript/reference/CRMScript.NetServer.NSTicketCategoryEntity.yml, docs/automation/crmscript/reference/CRMScript.NetServer.NSTicketEntity.yml, docs/automation/crmscript/reference/CRMScript.NetServer.NSTicketMessageEntity.yml, docs/automation/crmscript/reference/CRMScript.NetServer.NSUser.yml
=> Updating code examples #239

docs/automation/crmscript/reference/CRMScript.Native.StringObjectDictionary.yml, docs/automation/crmscript/reference/CRMScript.Native.yml, docs/automation/crmscript/reference/CRMScript.NetServer.NSWebhook.yml, docs/automation/crmscript/reference/CRMScript.NetServer.NSWebhookAgent.yml, docs/automation/crmscript/reference/toc.yml
=> #258 Fixed documentation

docs/api/web-services/so-timezone.md
Corrected misuse of plural form. Hope this is alright!
=> Updated the leading sentence

docs/ui/blogic/reference/ck-editor.md
Fix for https://github.com/SuperOfficeDocs/feedback/issues/65
=> Add documentation for retrieving attachment ids

docs/email/mailgun/sub-processor-info.md
=> #290 changed value of processing country for mailgun

docs/automation/crmscript/fundamentals/arrays.md, docs/automation/crmscript/fundamentals/structs.md
=> 292 add documentation for new methods on arrays structs

docs/automation/crmscript/reference/CRMScript.DataStructure.Array.yml, docs/automation/crmscript/reference/CRMScript.DataStructure.Struct.yml, docs/automation/crmscript/reference/toc.yml
Add CRMScript array and struct yaml reference.
=> Add CRMScript data structures array and struct, update toc #313

docs/automation/crmscript/reference/CRMScript.Global.String.yml
Updated documentation to make it more clear that methods to a letter by letter evaluation, and presence of none letters will return false.
=> #320 - Changed unclear descriptions

docs/api/logging/index.md
=> Fix xml declaration, #363

docs/email/Service.md
added how to change authentication on an existing mailbox
=> Update email for Service

docs/email/Service.md
Added updated requirements:
Unique/separate serial number for each site
=> Update OAuth requirement for Service

docs/identity-management/superid/howto/register-idp.md
Info added on "send welcome emails" w/url.
=> Updated regIdp

docs/automation/crmscript/reference/CRMScript.Native.XMLNode.yml
=> #387 Adding missing method in docs

docs/automation/crmscript/reference/CRMScript.Native.Rsa.yml
=> #413 Updated argument name

docs/email/Service.md
Update of note on version Up to  10.1.4: - effects and solution.
=> Update email in Service

docs/automation/crmscript/reference/CRMScript.Native.HtmlElement.yml, docs/automation/crmscript/reference/CRMScript.Native.MainMenu.yml
=> #424 Adding missing constructors

release-notes/database/changes-10.1.2.md, release-notes/database/changes-10.1.5.md
Temporary fix to keep the build checks happy until the tool gets updated
=> Fixed whitespace and MD036 in database changes

docs/email/Service.md
Added more troubleshooting and requirements to OAuth. and details to how it works
=> Update of Service - email

docs/automation/crmscript/datatypes/datetime-type.md, docs/automation/crmscript/reference/CRMScript.Global.DateTime.yml
=> #437 Added missing method

docs/online/version-history.md
Added 10.1.7 to Online version history
=> Online 10.1.7 version history

docs/automation/crmscript/datatypes/map-type.md, docs/automation/crmscript/reference/CRMScript.Native.Map.yml
=> #494 Added new method

docs/email/mailgun/overview.md
update a detail on How to configure with your own SMTP
=> update mailgun process

docs/automation/crmscript/datatypes/float-type.md, docs/automation/crmscript/datatypes/long-type.md, docs/automation/crmscript/reference/CRMScript.Global.Float.yml, docs/automation/crmscript/reference/CRMScript.Global.Integer.yml, docs/automation/crmscript/reference/CRMScript.Global.Long.yml, docs/automation/crmscript/reference/CRMScript.Global.String.yml, docs/automation/crmscript/reference/CRMScript.Global.yml, docs/automation/crmscript/reference/toc.yml
=> #511 Added new class file

docs/email/Service.md
Giving access to SO O365/Azure Enterprise App
=> update email in service register SO app

docs/automation/crmscript/reference/CRMScript.Global.Long.yml
=> #527 Fixing intellisense

docs/automation/crmscript/reference/CRMSCript.Native.EventDataDialogDefinition.yml, docs/automation/crmscript/reference/CRMScript.Native.StringObjectDictionary.yml
=> #499 Fixed issue with so.intellisense

docs/automation/crmscript/netserver/crmscript-archiveagent.md
=> #530 Added example for string version

docs/automation/crmscript/reference/CRMScript.NetServer.NSListAgent.yml, docs/automation/crmscript/reference/CRMScript.NetServer.NSTicketCategoryMembershipEntity.yml
=> #505 added new TicketCategoryMembershipEntity and new method

docs/onsite/version-history.md
Add skipped Onsite releases to overview
=> Update Onsite version list

docs/automation/crmscript/overview/crmscript-usage.md, docs/automation/index.yml, docs/automation/toc.yml
=> Convert automation to subcategory page

docs/online/version-history.md
=> Update Online releases

docs/email/Service.md, docs/email/inbox.md, docs/email/index.yml
My first update from a new notebook, I hope all is fine.
=> 563 enhance email category page

docs/en/identity-management/superid/idp-and-doc-handling.md
very old and incorrect info - update merely to remove the incorrect info.
=> update idp and doc handling

docs/en/document/cloud/sharepoint-documents/requirements.md
ALL users use IDP and use same Azure AD subscription
=> update requirements for SP2.0

docs/en/marketing/mailing/learn/create/includes/step-1-setup-email.md, release-notes/10.2/admin/10.2.2-update.md, release-notes/10.2/marketing/10.2.2-update.md
Added info about SPF validation for Online only in the What's new section for 10.2.2.
Added link to SPF in Step 1 of create email mailing.
=> #625 10.2.2 What's new - added Online info

docs/en/automation/crmscript/reference/CRMSCript.Native.EventDataDialogDefinition.yml
=> #623 Adding methods

docs/en/automation/crmscript/datatypes/map-type.md, docs/en/automation/crmscript/reference/CRMScript.Native.Map.yml
Fix for https://github.com/SuperOfficeDocs/feedback/issues/118
=> Fix casing of getWithFallBack method, should be getWithFallback

docs/en/onsite/version-history.md
Added 10.2.3 and 10.2.4 to Onsite releses
=> Added 10.2.3 and 4 to Onsite releses

docs/en/online/version-history.md
Add 10.2.4 to Online releases
Not sure why 10.2.3 branch was deleted by Tony, so please make sure both 10.2.3 and 4 are published.
=> Add 10.2.4 to Online releases

.github/workflows/build-help-pages.yml, docs/en/automation/crmscript/reference/CRMSCript.Native.EventDataDialogDefinition.yml, docs/en/automation/crmscript/reference/CRMScript.Native.EventDataDialogField.yml, docs/en/automation/crmscript/reference/CRMScript.Native.yml, docs/en/automation/crmscript/reference/toc.yml
=> #656 Adding type and methods

docs/en/identity-management/single-sign-on/onsite-sso.md
Add note about breaking changes in SuperOffice 10.1.5
=> Add note about changes in 10.1.5

docs/en/document/cloud/sharepoint-documents/configure-permissions-documents.md
Update sharepoint documents configurepermissions-document with details about Confidential activities and Visible for
=> Update sharepoint documents configurepermissions-document

docs/en/document/cloud/sharepoint-documents/troubleshooting.md
added info on how to remove permissions from  the Enterprise Application "SuperOffice Document Library"
=> update troubleshooting SP2.0

docs/en/document/cloud/sharepoint-documents/configure-permissions-templates.md, docs/en/document/cloud/sharepoint-documents/configure-superoffice.md, docs/en/document/cloud/sharepoint-documents/includes/req-general.md, docs/en/document/cloud/sharepoint-documents/includes/req-usage.md, docs/en/document/cloud/sharepoint-documents/index.md, docs/en/document/cloud/sharepoint-documents/permissions-in-sharepoint.md, docs/en/document/cloud/sharepoint-documents/requirements.md, docs/en/document/cloud/sharepoint-documents/set-up.md
=> 693 update sharepoint index

docs/en/ui/soprotocol/used-in-webpanels-web.md
Issue: https://github.com/SuperOfficeDocs/feedback/issues/110
=> feedback-110 add link to crossmessaging sample

docs/en/api/search/find-selection/operators.md
Product change that missed getting updated in docs...
=> Update operators.md #724

docs/en/marketing/learn/index.md, docs/no/marketing/learn/index.md
https://github.com/SuperOfficeDocs/feedback/issues/122
=> removed line stating SMS mailing is not part of online

docs/en/document/templates/variables/for-quote-line-with-subscription.md
=> #707 Add download link to quote template PDF

docs/en/faq/learn/index.md
was an extra '1' there - removed
=> Update work with FAQ - type-O

docs/en/dashboard/learn/index.md, docs/en/request/learn/external-document.md, docs/en/request/learn/howto/create.md, docs/en/request/learn/howto/forward.md, docs/en/request/learn/howto/reply.md, docs/en/request/learn/index.md, docs/en/request/learn/screen/knowledge-base.md
Update of the folder for request with different issues
#763 + branch
33. Add info/chapt about Add comment | request/learn/howto/reply.html - DONE
34. To Details headinger, fjern nederste | request/learn/howto/create.html - DONE
43. Knowledge base: Fjerne noen punkter som ikke lenger er der - request/learn/screen/knowledge-base.html - DONE
42. FAQ: Add Note på Premium service eller ekstra lisens for Customer centre faq/learn/index.html - NOT done, since it's an include file.
46. FAQ: Typo i heading Rep1ly... | faq/learn/index.html - DONE by Frode in June-23
44. Requests: Legg til contacts i listen over hvor request tab er synlig | request/learn/index.html#where-can-i-access-requests - DONE
47. Requests: Oppdater med files og ikke document i første setning | …
=> #763 Learn update of requests, faq, dashboard

docs/en/admin/import/learn/configure-import-settings.md, docs/en/admin/import/learn/index.md, docs/en/admin/import/learn/toc.yml, docs/en/admin/license/learn/index.md, docs/en/admin/lists/learn/add-template.md, docs/en/admin/lists/learn/adding-items.md, docs/en/admin/lists/learn/creating-template-document.md, docs/en/admin/lists/learn/document-template.md, docs/en/admin/lists/learn/replace-existing-template.md, docs/en/admin/lists/learn/specialized-lists.md, docs/en/admin/lists/learn/toc.yml, docs/en/admin/lists/learn/using-standard-templates.md, docs/en/admin/user-management/learn/user-groups.md, docs/en/custom-objects/learn/toc.yml, docs/en/document/learn/template-variables.md, docs/en/onsite/win-client/learn/using-document-templates-for-multiple-languages.md, docs/en/ui/screen-designer/learn/add-new-layout.md
Finished update of Admin sections for Learn - see #765 for more details
=> 765 learn update admin folders

docs/en/mirroring/force-resync.md, docs/nl/admin/lists/learn/adding-items.md, docs/nl/request/learn/category/index.md, docs/nl/request/learn/howto/toc.yml, docs/nl/request/learn/tags.md
'Tags' should be translated to 'Labels' (same as in the GUI)
=> Fix dutch learn translation errors

docs/da/learn/getting-started/preferences.md, docs/de/learn/getting-started/preferences.md, docs/en/learn/getting-started/preferences.md, docs/nl/learn/getting-started/preferences.md, docs/no/learn/getting-started/preferences.md, docs/sv/learn/getting-started/preferences.md
* Added in-app row to table
* Added so.audience metadata
* Added link to global preferences
=> #807 Add in-app preference to table

docs/en/automation/crmscript/reference/CRMScript.Native.ExtraTable.yml
Based on feedback from @acdavidh, updated examples for ExtraTable class.
=> Updated examples for ExtraTable based on forum/issue feedback #831

docs/en/online/version-history.md
=> Add 10.2.7 to Online

docs/en/webtools/learn/install.md
Fix https://github.com/SuperOfficeDocs/feedback/issues/135
=> Remove wrong reference to macos package and auto number list

docs/en/online/version-history.md
=> Add 10.2.9 to Online

docs/en/document/cloud/sharepoint-documents/migrate/index.md
more info on "Migrate from Microsoft 365 Document Integration (legacy)" as there are some manual steps and some updated info on consequences of the change.
=> Update Migrate from Microsoft 365 Document Integration (legacy)

docs/en/email/mailgun/spf/index.md
Fix typoes and highlight info about SPF in Online.
=> Update SPF page

docs/en/developer-portal/standard-app/app-store/images-and-videos.md
Proposed changes for issue #899 .
=> Update dev portal partner and app images and videos

release-notes/eol/index.md, release-notes/eol/lotus.md, release-notes/eol/pagebuilder.md, release-notes/eol/soap.md, release-notes/eol/toc.yml, release-notes/toc.yml
=> #926 Add EOL section in release notes

release-notes/10.2/api/10.2.9-update.md
Change text for 10.2.9 api release notes, released for both online and onsite
Fix for #940
=> Change text for 10.2.9 api release notes 

docs/en/automation/webhook/reference/ticket-events.md
=> Updated with new support for field changes in event

docs/en/developer-portal/widgets/index.md
Add and publish for the 1.17 release 15.12.2023.
=> Update available widgets - include New Customers.

docs/da/admin/erp/learn/includes/req-integration-server.md, docs/da/admin/erp/learn/screen/erp-tab.md, docs/da/learn/includes/erp-tab.md, docs/da/quote/learn/admin/index.md, docs/da/search-options/learn/find-screen.md, docs/de/admin/erp/learn/includes/req-integration-server.md, docs/de/admin/erp/learn/screen/erp-tab.md, docs/de/learn/includes/erp-tab.md, docs/de/quote/learn/admin/index.md, docs/de/search-options/learn/find-screen.md, docs/en/admin/erp/learn/includes/req-integration-server.md, docs/en/admin/erp/learn/screen/erp-tab.md, docs/en/learn/includes/erp-tab.md, docs/en/quote/learn/admin/index.md, docs/en/search-options/learn/find-screen.md, docs/nl/admin/erp/learn/includes/req-integration-server.md, docs/nl/admin/erp/learn/screen/erp-tab.md, docs/nl/learn/includes/erp-tab.md, docs/nl/quote/learn/admin/index.md, docs/nl/search-options/learn/find-screen.md, docs/no/admin/erp/learn/includes/req-integration-server.md, docs/no/admin/erp/learn/screen/erp-tab.md, docs/no/learn/includes/erp-tab.md, docs/no/quote/learn/admin/index.md, docs/no/search-options/learn/find-screen.md, docs/sv/admin/erp/learn/screen/erp-tab.md, docs/sv/learn/includes/erp-tab.md, docs/sv/quote/learn/admin/index.md, docs/sv/search-options/learn/find-screen.md
=> Update license req for quote/sync #872

release-notes/eol/index.md, release-notes/eol/soap.md
- Added row to archive list in EOL overview
- Added section to existing SOAP EOL page
- Fixed uid bug
=> Add CS SOAP to EOL #962

docs/en/developer-portal/standard-app/certification/initial-watchcom-eval.md
- rewrote section *How is the testing done?*
- added column "Extended" to table and updated prices
- added note to step 7
- clarified "our" a few places and fixed typo "Wathcom"
=> #933 updated security evaluation page

docs/en/document/cloud/sharepoint-documents/index.md
added warning info - password users cannot log in when enabling ZFP
=> update to to general info on ZFP

docs/da/marketing/forms/learn/toc.yml, docs/de/marketing/forms/learn/toc.yml, docs/en/marketing/forms/learn/toc.yml, docs/nl/marketing/forms/learn/toc.yml, docs/no/marketing/forms/learn/toc.yml, docs/sv/marketing/forms/learn/toc.yml
**Must delete *_site* and *obj* before building for this change to take effect.**
=> Add href for form-templates and submissions/index #1035

.github/workflows/ci.yml
See https://github.com/markdownlint/markdownlint/issues/472
=> Omit reverted markdownlint rules

release-notes/10.3/admin/10.3.1-update.md, release-notes/10.3/admin/index.md, release-notes/10.3/core-crm/10.3.1-update.md, release-notes/10.3/core-crm/index.md, release-notes/10.3/index.md, release-notes/10.3/service/index.md, release-notes/10.3/toc.yml, release-notes/index.md
Have removed request dashboard chapter, but not the images, since this will be available from 10.3.2.
Changed release date of 10.3.1
Changed some minor text and added info about Office integration release info.
=> #1046 Updated date for 10.3.1 release + remove of not released info

docs/en/automation/crmscript/reference/CRMScript.NetServer.NSPersonEntity.yml
=> #1053 Removing methods

docs/da/company/learn/create.md, docs/de/company/learn/create.md, docs/de/mobile/superoffice-mobile/reply-to-request.md, docs/en/api/entities/howto/custom-objects/get-udef-field-value.md, docs/en/automation/crmscript/overview/crmscript-usage.md, docs/en/company/learn/create.md, docs/en/developer-portal/create-app/server-to-server-app.md, docs/en/developer-portal/create-app/sync-app.md, docs/en/developer-portal/standard-app/app-store/update-app-page.md, docs/en/document/cloud/sharepoint-documents/configure-superoffice.md, docs/en/search-options/index.yml, docs/nl/company/learn/create.md, docs/nl/mobile/superoffice-mobile/reply-to-request.md, docs/no/company/learn/create.md, docs/no/mobile/superoffice-mobile/reply-to-request.md, docs/sv/company/learn/create.md, docs/sv/mobile/superoffice-mobile/reply-to-request.md, release-notes/10.3/service/index.md, release-notes/mobile/includes/request-type-update.md
NOTE: also need https://github.com/SuperOfficeDocs/build-docs/pull/100 and https://github.com/SuperOfficeDocs/build-docs/pull/99 to trim the list of warnings down to API references
=> Bug fix links

docs/en/document/cloud/sharepoint-documents/migrate/index.md
Update index to include a link to how to add Apps for SuperOffice (system user)
=> Update index include link  add system user

docs/en/webtools/config.md
Adding WebTools commit overlooked last time we merged
=> Update config.md - add ProxyUrl

docs/en/developer-portal/analytics/includes/improve-performance.md
=> Fix spelling mistake

docs/en/email/inbox/index.md
Also added uid and formatted instructions for how to add featuretoggle (was invalid markdown)
=> Remove MailKit version

release-notes/10.3/index.md, release-notes/index.md, release-notes/mobile/toc.yml
No new features/functions
Added Pilot program in main index.md
Changed toc for Mobile - where 10.1 and 10.0 releases is added as a sub chapter.
=> #1139 - Release notes, just updates of index pages + mobile toc

docs/en/online/system-requirements.md
=> Clarified attachment max size is per request message #1156 

docs/en/automation/crmscript/reference/CRMScript.Global.String.yml
=> Updating #1123 with suggestions

docs/en/automation/crmscript/reference/CRMScript.Native.EventDataDialogDefinition.yml
=> Updated EventDataDialogDefinition #1186

docs/en/automation/crmscript/reference/CRMScript.Native.EventDataDialogDefinition.yml
Cherry-picked update from a previously merged branch. Replaces PR #1190. Solution discussed with @kronicz
=> Updated CRMScript example eventdatadialogdefinition

docs/en/marketing/flows/learn/define-flow-actions.md, docs/en/marketing/flows/learn/index.md, docs/en/marketing/flows/learn/split.md, docs/en/marketing/flows/learn/view-statistics.md, docs/en/marketing/learn/index.md, docs/no/admin/license/learn/index.md, docs/no/admin/license/learn/screen/index.md, docs/no/admin/user-management/learn/role/functional-rights.md, docs/no/marketing/editor/learn/edit-paragraph.md, docs/no/marketing/flows/learn/content.md, docs/no/marketing/flows/learn/create.md, docs/no/marketing/flows/learn/define-flow-actions.md, docs/no/marketing/flows/learn/index.md, docs/no/marketing/flows/learn/participants.md, docs/no/marketing/flows/learn/run-pause-end.md, docs/no/marketing/flows/learn/split.md, docs/no/marketing/flows/learn/step-settings.md, docs/no/marketing/flows/learn/toc.yml, docs/no/marketing/flows/learn/update.md, docs/no/marketing/flows/learn/view-statistics.md, docs/no/marketing/forms/learn/define-form-actions.md, docs/no/marketing/learn/best-practices.md, docs/no/marketing/learn/create-folder.md, docs/no/marketing/learn/index.md, docs/no/marketing/learn/toc.yml, docs/no/marketing/tracked-links/learn/define-link-actions.md
Detected and fixed a few formatting bugs in both EN and NO while reviewing.
=> Initial Norwegian translation of flows #1188 

docs/de/admin/license/learn/index.md, docs/de/admin/license/learn/screen/index.md, docs/de/admin/user-management/learn/role/functional-rights.md, docs/de/learn/getting-started/connect-email-doc/index.md, docs/de/learn/section-tabs/filter.md, docs/de/marketing/flows/learn/content.md, docs/de/marketing/flows/learn/create.md, docs/de/marketing/flows/learn/define-flow-actions.md, docs/de/marketing/flows/learn/index.md, docs/de/marketing/flows/learn/participants.md, docs/de/marketing/flows/learn/run-pause-end.md, docs/de/marketing/flows/learn/split.md, docs/de/marketing/flows/learn/step-settings.md, docs/de/marketing/flows/learn/toc.yml, docs/de/marketing/flows/learn/update.md, docs/de/marketing/flows/learn/view-statistics.md, docs/de/marketing/forms/learn/define-form-actions.md, docs/de/marketing/learn/best-practices.md, docs/de/marketing/learn/create-folder.md, docs/de/marketing/learn/index.md, docs/de/marketing/learn/toc.yml, docs/de/marketing/tracked-links/learn/define-link-actions.md, docs/de/project/learn/project-guide/working-with.md, docs/en/marketing/flows/learn/index.md
FYI: 6 of the pages are just formatting bug fixes
=> Translate flows to German #1189

docs/da/marketing/flows/learn/content.md, docs/da/marketing/flows/learn/create.md, docs/da/marketing/flows/learn/define-flow-actions.md, docs/da/marketing/flows/learn/index.md, docs/da/marketing/flows/learn/participants.md, docs/da/marketing/flows/learn/run-pause-end.md, docs/da/marketing/flows/learn/split.md, docs/da/marketing/flows/learn/step-settings.md, docs/da/marketing/flows/learn/update.md, docs/da/marketing/flows/learn/view-statistics.md, docs/nl/marketing/flows/learn/content.md, docs/nl/marketing/flows/learn/create.md, docs/nl/marketing/flows/learn/define-flow-actions.md, docs/nl/marketing/flows/learn/index.md, docs/nl/marketing/flows/learn/participants.md, docs/nl/marketing/flows/learn/run-pause-end.md, docs/nl/marketing/flows/learn/split.md, docs/nl/marketing/flows/learn/step-settings.md, docs/nl/marketing/flows/learn/update.md, docs/nl/marketing/flows/learn/view-statistics.md, docs/sv/marketing/flows/learn/content.md, docs/sv/marketing/flows/learn/create.md, docs/sv/marketing/flows/learn/define-flow-actions.md, docs/sv/marketing/flows/learn/index.md, docs/sv/marketing/flows/learn/participants.md, docs/sv/marketing/flows/learn/run-pause-end.md, docs/sv/marketing/flows/learn/split.md, docs/sv/marketing/flows/learn/step-settings.md, docs/sv/marketing/flows/learn/update.md, docs/sv/marketing/flows/learn/view-statistics.md
Must delete _site and obj folders before building. Otherwise, the redirects won't be updated.
=> #1206 fix lang in flow redirect URLs

docs/en/api/config/data.md, docs/en/api/config/documents.md, docs/en/api/config/index.md, docs/en/api/config/webapi.md
Added ArchiveRelativePath, TemplateRelativePath and TemporaryRelative path to documents.md
=> Added the missing parameters, with descriptions

docs/en/api/authentication/online/auth-application/index.md, docs/en/api/authentication/online/certificates/index.md, docs/en/api/authentication/online/certificates/override-resolver.md, docs/en/api/authentication/online/sign-in-user/implicit-flow.md, docs/en/api/authentication/online/validate-security-tokens.md
…esolver, and points to override-resolver.md which explains it/how.
=> Add note linking to override certificate resolver

docs/en/email/mailgun/overview.md
add info on using shared mailbox for mail forward
=> Update mailgun option 2

docs/da/learn/getting-started/connect-email-doc/index.md, docs/de/learn/getting-started/connect-email-doc/index.md, docs/en/learn/getting-started/connect-email-doc/index.md, docs/nl/learn/getting-started/connect-email-doc/index.md, docs/no/learn/getting-started/connect-email-doc/index.md, docs/sv/learn/getting-started/connect-email-doc/index.md
Missing some information in the Email, Document, Calendar section. 
Some minor image text errors.
=> Learn - Connect email, doc and calender - Update index.md

docs/en/ai/index.md
Removed text about requirement: sign up to Pilot (as only AI Lab, not AI Services have this req.)
=> Update AI Services

docs/en/automation/trigger/reference/CRMScript.Event.Trigger.yml
=> Added new trigger #1248

docs/en/automation/crmscript/reference/CRMScript.Native.Ticket.yml, docs/en/request/howto/crmscript/create.md
=> Removing not supported method #1264

docs/da/company/learn/address-formats.md, docs/de/company/learn/address-formats.md, docs/en/company/learn/address-formats.md, docs/nl/company/learn/address-formats.md, docs/no/company/learn/address-formats.md, docs/sv/company/learn/address-formats.md
rewrite intro, update metadata, move UK (so it belongs to Europe)
=> Correct number of address formats #1276

docs/da/email/service/learn/email-filters/create-email-filter.md, docs/de/email/service/learn/email-filters/create-email-filter.md, docs/en/email/service/learn/email-filters/create-email-filter.md, docs/nl/email/service/learn/email-filters/create-email-filter.md, docs/no/email/service/learn/email-filters/create-email-filter.md, docs/sv/email/service/learn/email-filters/create-email-filter.md
Also updated metadata (more keywords)
=> Change email filter priority max to 100 #1277

docs/en/ui/soprotocol/custom-object.md, docs/en/ui/soprotocol/navigation-points.md, docs/en/ui/soprotocol/toc.yml
Closing https://github.com/SuperOfficeDocs/superoffice-docs/issues/1256
=> Added new information #226

docs/da/custom-objects/learn/udef.md, docs/de/custom-objects/learn/udef.md, docs/en/custom-objects/learn/udef.md, docs/nl/custom-objects/learn/udef.md, docs/no/custom-objects/learn/udef.md, docs/sv/custom-objects/learn/udef.md
(English text reviewed by @MargretheR )
=> Update info about max available fields and indexing #1258

release-notes/mobile/index.md
Mobile CRM was rewritten from Xamarin to MAUI
=> Update mobile CRM release notes

docs/en/automation/crmscript/reference/CRMScript.NetServer.NSArchiveAgent.yml
=> #1381 Updating CRMScript reference

docs/en/security/privacy/soft-delete.md
Re-structured the soft-delete documentation and added additional information for which tables and fields are affected by a hard-delete. This should improve the readers understanding of what actually happens behind the scenes.
=> 483 feedback for soft delete

release-notes/eol/index.md
Update date and status for EOL Reporter
=> Update EOL Reporter

docs/en/automation/crmscript/reference/CRMScript.NetServer.NSDash.yml, docs/en/automation/crmscript/reference/CRMScript.NetServer.NSDashAgent.yml, docs/en/automation/crmscript/reference/CRMScript.NetServer.NSDashCollection.yml, docs/en/automation/crmscript/reference/CRMScript.NetServer.NSDashTheme.yml, docs/en/automation/crmscript/reference/CRMScript.NetServer.NSDashTile.yml, docs/en/automation/crmscript/reference/CRMScript.NetServer.NSDashTileDefinition.yml, docs/en/automation/crmscript/reference/CRMScript.NetServer.NSDashTileHtml.yml, docs/en/automation/crmscript/reference/CRMScript.NetServer.NSPreviewDash.yml, docs/en/automation/crmscript/reference/CRMScript.NetServer.NSPreviewDashTile.yml, docs/en/automation/crmscript/reference/CRMScript.NetServer.yml, docs/en/automation/crmscript/reference/toc.yml
=> Adding new Agent #1468

docs/sv/diary/learn/follow-ups.md
Missing a space between "för" and "möte".
It might be more missing spaces, but have not double checked it.
=> SV - Update follow-ups.md

docs/da/search-options/selection/learn/howto/print.md, docs/de/search-options/selection/learn/howto/print.md, docs/en/search-options/selection/learn/howto/print.md, docs/nl/search-options/selection/learn/howto/print.md, docs/no/search-options/selection/learn/howto/print.md, docs/sv/search-options/selection/learn/howto/print.md
There is some issues with the TOC on this page - Shows Print company reports, but that is no longer in place and clicking it, will open this page - but then the toc won't follow.
=> Learn - Selection tasks - Update print.md

docs/en/automation/crmscript/reference/CRMScript.NetServer.NSPersonAgent.yml, docs/en/automation/crmscript/reference/CRMScript.NetServer.NSSentryAgent.yml
=> Updating return types

release-notes/10.3/index.md, release-notes/index.md
Minor changes for the 10.3.13 release.
=> 1536 10.3.13 release notes

docs/da/marketing/flows/learn/run-pause-end.md, docs/de/marketing/flows/learn/run-pause-end.md, docs/en/marketing/flows/learn/run-pause-end.md, docs/nl/marketing/flows/learn/run-pause-end.md, docs/no/marketing/flows/learn/run-pause-end.md, docs/sv/marketing/flows/learn/run-pause-end.md
=> #1723 Update how to delete flow

docs/da/learn/getting-started/main-screen/navigator.md, docs/da/marketing/flows/learn/step-settings.md, docs/da/onsite/win-client/learn/using-document-templates-for-multiple-languages.md, docs/da/project/learn/index.md, docs/da/project/learn/project-guide/index.md, docs/da/project/learn/screen/project-guide-admin.md, docs/da/sale/learn/sales-guide/index.md, docs/da/sale/learn/sales-guide/sales-guide-tab.md
Reported for project guide but fixed sales guide too.
=> #1658 Fix DA translation bug

docs/en/email/superoffice-for-outlook/it/deploy.md
we don't support via custom xml file any longer. This change is initiated by Erik Lebiko.
=> Update deploy to remove customized section

docs/en/onsite/feature-toggles.md
Update feature-toggles list with latest FTs
=> Update feature-toggles list

docs/en/document/cloud/sharepoint-documents/migrate/index.md
remove 20 000 files restriction
=> Update ZFP mig BP

release-notes/10.5/index.md, release-notes/index.md
Only bug fixes - no new or changed features or functions.
Changed 2 index files.
=> #1840 Changes to release info

docs/en/automation/crmscript/reference/CRMScript.Global.DateTime.yml, docs/en/automation/crmscript/reference/CRMScript.Global.Void.yml, docs/en/automation/crmscript/reference/CRMScript.Native.HTTP.yml, docs/en/automation/crmscript/reference/CRMScript.NetServer.NSAppointment.yml, docs/en/automation/crmscript/reference/CRMScript.NetServer.NSArchiveColumnInfo.yml, docs/en/automation/crmscript/reference/CRMScript.NetServer.NSChatAgent.yml, docs/en/automation/crmscript/reference/CRMScript.NetServer.NSDepartment.yml, docs/en/automation/crmscript/reference/CRMScript.NetServer.NSFindResults.yml, docs/en/automation/crmscript/reference/CRMScript.NetServer.NSKbCategory.yml, docs/en/automation/crmscript/reference/CRMScript.NetServer.NSLocalizedText.yml
Removed typos/extra `"` and `'` from end of type definition/references
=> Removed typos/extra " and ' from end of type definition/references

docs/en/automation/crmscript/reference/CRMScript.Native.EventDataDialogDefinition.yml
=> Added new methods

docs/da/sale/learn/forecasting.md, docs/de/sale/learn/forecasting.md, docs/en/sale/learn/forecasting.md, docs/nl/sale/learn/forecasting.md, docs/no/sale/learn/forecasting.md, docs/sv/sale/learn/forecasting.md
* Cut the "compared to last year" part of the tile's name in all languages.
* Fixed placement of bold formatting where needed.
* Set today's date but version 10.4 to signal it's not yet been updated for new ux.
=> #1908 Update name of tile

docs/en/mirroring/getting-started/index.md
old package deprecated, updated link references new package
=> Updated reference to Mirroring on nuget.org

docs/da/admin/lists/learn/add-items-to-country-list.md, docs/de/admin/lists/learn/add-items-to-country-list.md, docs/en/admin/lists/learn/add-items-to-country-list.md, docs/nl/admin/lists/learn/add-items-to-country-list.md, docs/nl/admin/lists/learn/includes/note-mandatory-field.md, docs/no/admin/lists/learn/add-items-to-country-list.md, docs/sv/admin/lists/learn/add-items-to-country-list.md
* Cut step 2 in country list (edit appears more extensive than it is since all subsequent steps must be renumbered)
* Fix bug - nested note include
* Fix capitalization in Dutch include text
* Update metadata
=> #1735 Remove English name step from country list

docs/da/sale/learn/create.md, docs/da/sale/learn/index.md, docs/de/sale/learn/create.md, docs/de/sale/learn/index.md, docs/en/sale/learn/create.md, docs/en/sale/learn/index.md, docs/nl/sale/learn/create.md, docs/nl/sale/learn/index.md, docs/no/sale/learn/create.md, docs/no/sale/learn/index.md, docs/sv/sale/learn/create.md, docs/sv/sale/learn/index.md
=> #1653 State where to find preference

docs/da/marketing/recipients/learn/manage-bounces.md, docs/de/marketing/recipients/learn/manage-bounces.md, docs/en/marketing/recipients/learn/manage-bounces.md, docs/nl/marketing/recipients/learn/manage-bounces.md, docs/no/marketing/recipients/learn/manage-bounces.md, docs/sv/marketing/recipients/learn/manage-bounces.md
Expand blocked email addresses section
Update metadata
=> #1652 Explain too many bounces

docs/de/diary/learn/recurrence/create.md, docs/en/admin/user-preferences/reference/netservices.md, docs/en/automation/crmscript/howto/contact/get-interests.md, docs/en/automation/webhook/reference/index.md, docs/en/diary/learn/recurrence/stop.md, docs/en/travel/sybase/set-up.md, docs/en/ui/soprotocol/index.md
=> #2036 Remove duplicate frontmatter properties

docs/en/admin/user-preferences/add-prefdesc.md, docs/en/api/lists/services/mdoagent/mdo-how-to.md, docs/en/api/lists/sql/add-list-item-sql.md, docs/en/api/logging/configure-serilog.md, docs/en/api/plugins/quote-connectors/adding-products.md, docs/en/api/plugins/quote-connectors/start-client.md, docs/en/api/web-services/howto/custom-objects/rest-create-udef-field.md, docs/en/ui/web-app/tutorials/ajax-create-followup/index.md, docs/en/ui/web-panels/add-web-panel.md
Also, improved metadata in files touched.
=> #2038 Fix line length errors (MD013)

docs/no/ui/blogic/learn/extra-menus/actions.md, docs/no/ui/blogic/learn/extra-menus/index.md, docs/no/ui/blogic/learn/extra-menus/navigator.md, docs/no/ui/blogic/learn/extra-menus/properties.md, docs/no/ui/blogic/learn/includes/legacy-extra-menus.md, docs/no/ui/blogic/learn/includes/legacy-profiles.md
Same problem in legacy-extra-menus.md and legacy-profiles.md
=> #2070 Fix nested note in NO blogic

docs/da/learn/index.yml, docs/de/learn/index.yml, docs/en/diary/index.yml, docs/en/learn/index.yml, docs/en/project/index.yml, docs/nl/learn/index.yml, docs/no/learn/index.yml, docs/sv/learn/index.yml
* Also update translations, using LANG/diary/learn/create-follow-up.md as guide.
* Found 2 more occurrences outside learn.
=> #2162 Appointment > Follow-up

docs/da/learn/customization.yml, docs/de/learn/customization.yml, docs/en/learn/customization.yml, docs/nl/learn/customization.yml, docs/no/learn/customization.yml, docs/sv/learn/customization.yml
Simply removing the 3 lines that started a new list
=> #2163 Merge same-type link lists

docs/da/search-options/selection/learn/board-view.md, docs/de/search-options/selection/learn/board-view.md, docs/en/search-options/selection/learn/board-view.md, docs/nl/search-options/selection/learn/board-view.md, docs/no/search-options/selection/learn/board-view.md, docs/sv/search-options/selection/learn/board-view.md
* search-options/selection/learn/board-view.md
* Remove the sentence about limited availability
* Add a list of filters (examples, not exhaustive)
* Add use cases for project and request actors
* Add related content
=> #2173 board view for projects and  requests

docs/da/learn/basics/notifications.md, docs/de/learn/basics/notifications.md, docs/en/learn/basics/notifications.md, docs/nl/learn/basics/notifications.md, docs/no/learn/basics/notifications.md, docs/sv/learn/basics/notifications.md
* learn/basics/notifications.md
* Add new preference
* Refactor the browser notification section to use horizontal tabs
* Fix Danish terminology to match UI (bug #2157) - while editing the page, anyway
* Fix the Norwegian preference name to match the UI (line 73/75)
=> #1946 Add new ownership notification

docs/en/ui/soprotocol/howto/create-follow-up.md
appointmenttask_name is not useable. tasktype is correct to set the tasktype
=> Removed appointmenttask_name and added tasktype in documentation

docs/de/sale/learn/sales-targets/target-types.md, docs/no/sale/learn/sales-targets/target-types.md, docs/sv/sale/learn/sales-targets/target-types.md, release-notes/10.0/api/10.0.6-update.md, release-notes/11/api/11.2/11.2-netserver-update.md, release-notes/11/api/11.2/11.2-webapi-update.md, release-notes/11/api/11.2/includes/changes-11.2.487-netserver.md, release-notes/11/api/11.3/11.3-netserver-update.md, release-notes/11/api/11.3/11.3-webapi-update.md, release-notes/11/api/11.3/includes/changes-netserver-11.3.1348.0.md, release-notes/11/api/11.3/includes/changes-netserver-11.3.1349.0.md, release-notes/11/api/11.3/includes/changes-webapi-11.3.1348.0.md, release-notes/11/api/11.3/includes/changes-webapi-11.3.1349.0.md, release-notes/11/api/11.4/11.4-netserver-update.md, release-notes/11/api/11.4/11.4-webapi-update.md, release-notes/11/api/11.4/includes/changes-netserver-11.4.1157.0.md, release-notes/11/api/11.4/includes/changes-webapi-11.4.1157.0.md, release-notes/9.2/api/9.2-R06-update.md, release-notes/9.2/cep/index.md
Includes should never have metadata
=> #2303 bug duplicate uids

docs/en/mobile/superoffice-mobile/caller-id.md, docs/en/mobile/superoffice-mobile/index.md, docs/en/mobile/superoffice-mobile/interface-guide.md, docs/en/mobile/superoffice-mobile/login.md, docs/en/mobile/superoffice-mobile/set-up-email.md, docs/en/mobile/superoffice-mobile/settings.md
Added the most important pages in Mobile CRM to be indexed in Userflow
=> #2334 Added index: true to the 6 most important pages
